// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJDNn0cDs8EW05buew06M3oNmrFCM7dTM',
    appId: '1:1060542705503:web:3d8c28437c534031c110ea',
    messagingSenderId: '1060542705503',
    projectId: 'filmflowapp-3e8cb',
    authDomain: 'filmflowapp-3e8cb.firebaseapp.com',
    storageBucket: 'filmflowapp-3e8cb.firebasestorage.app',
    measurementId: 'G-NSQDHLL7HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Z1QxEcMaWuvVfuyuBYtmgDiByso5xUU',
    appId: '1:1060542705503:android:fcf34b5c4127ef3ac110ea',
    messagingSenderId: '1060542705503',
    projectId: 'filmflowapp-3e8cb',
    storageBucket: 'filmflowapp-3e8cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7MHJe5ob4UuBlgKyVvNQNNytb5StD0H4',
    appId: '1:1060542705503:ios:7c329ded8a135394c110ea',
    messagingSenderId: '1060542705503',
    projectId: 'filmflowapp-3e8cb',
    storageBucket: 'filmflowapp-3e8cb.firebasestorage.app',
    iosBundleId: 'com.example.filmappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7MHJe5ob4UuBlgKyVvNQNNytb5StD0H4',
    appId: '1:1060542705503:ios:7c329ded8a135394c110ea',
    messagingSenderId: '1060542705503',
    projectId: 'filmflowapp-3e8cb',
    storageBucket: 'filmflowapp-3e8cb.firebasestorage.app',
    iosBundleId: 'com.example.filmappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJDNn0cDs8EW05buew06M3oNmrFCM7dTM',
    appId: '1:1060542705503:web:251fa89e83ddeea4c110ea',
    messagingSenderId: '1060542705503',
    projectId: 'filmflowapp-3e8cb',
    authDomain: 'filmflowapp-3e8cb.firebaseapp.com',
    storageBucket: 'filmflowapp-3e8cb.firebasestorage.app',
    measurementId: 'G-ZZWNV97XE6',
  );
}
